import { readFile, writeFile, mkdir, realpath, lstat, rename, unlink } from 'node:fs/promises';
import { dirname, resolve, relative, isAbsolute, join } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import SwaggerParser from '@apidevtools/swagger-parser';
import type { OpenAPI } from 'openapi-types';
import { parse } from 'yaml';
import { normalizeResources,normalizeRequests, type OpenApiDocument, type ResourceSelection,type RequestSelection } from '@mpfrontend/ftg-core';
import {readModelOutputs,requestModelOutputs} from './read-models.js';
export const GENERATOR_VERSION='0.1.0-dev.6';
export const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
export class InputError extends Error { constructor(message:string,readonly exitCode=2){super(message);} }
export type GeneratorConfig={ openapi:string;output:string;resources:ResourceSelection[];requests?:RequestSelection[] };
const HEADER='// @generated by FTG; edit authored overrides instead.\n';
function containsExternalRef(value:unknown):boolean {
  if(!value || typeof value!=='object')return false;
  if(Array.isArray(value))return value.some(containsExternalRef);
  const object=value as Record<string,unknown>;
  if(typeof object.$ref==='string' && !object.$ref.startsWith('#/'))return true;
  return Object.values(object).some(containsExternalRef);
}
export async function loadContract(path:string):Promise<{document:OpenApiDocument;bytes:string;hash:string}>{
  const bytes=await readFile(path,'utf8');
  if(Buffer.byteLength(bytes)>5*1024*1024)throw new InputError('CONTRACT_TOO_LARGE');
  const document=parse(bytes) as OpenApiDocument;
  if(!document || typeof document.openapi!=='string' || !document.openapi.startsWith('3.'))throw new InputError('INVALID_OPENAPI');
  if(containsExternalRef(document))throw new InputError('EXTERNAL_REFS_REQUIRE_PINNED_BUNDLE');
  await SwaggerParser.validate(document as OpenAPI.Document,{resolve:{external:false}});
  return {document,bytes,hash:digest(bytes)};
}
async function safeOutput(base:string,output:string):Promise<string>{
  const canonical=await realpath(base);
  const target=resolve(canonical,output);
  if(isAbsolute(output) || relative(canonical,target).startsWith('..') || target===canonical)throw new InputError('OUTPUT_OUTSIDE_CONFIG_ROOT',4);
  let existing=target;
  while(true){
    try { const actual=await realpath(existing);if(relative(canonical,actual).startsWith('..'))throw new InputError('SYMLINK_OUTPUT_ESCAPE',4);break; }
    catch(error){if(error instanceof InputError)throw error;if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;existing=dirname(existing);}
  }
  return target;
}
async function generatedFile(file:string):Promise<string|undefined>{
  try{if((await lstat(file)).isSymbolicLink())throw new InputError('GENERATED_FILE_SYMLINK',4);return await readFile(file,'utf8');}
  catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return undefined;throw error;}
}
async function assertNoWriter(marker:string){
  try{await lstat(marker);throw new InputError('GENERATION_BUSY',4);}
  catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
}
export async function generate(configPath:string,{check=false,dryRun=false}:{check?:boolean;dryRun?:boolean}={}){
  const base=dirname(resolve(configPath));
  const raw=JSON.parse(await readFile(configPath,'utf8')) as GeneratorConfig;
  if(typeof raw.openapi!=='string' || typeof raw.output!=='string' || !Array.isArray(raw.resources))throw new InputError('INVALID_CONFIG');
  if(raw.requests!==undefined&&!Array.isArray(raw.requests))throw new InputError('INVALID_REQUEST_CONFIG');
  const output=await safeOutput(base,raw.output);
  const {document,hash}=await loadContract(resolve(base,raw.openapi));
  const resources=normalizeResources(document,raw.resources);
  const requests=normalizeRequests(document,raw.requests??[]);
  const source=HEADER+'import type { ResourceModel } from "@mpfrontend/ftg-core";\n'+
    'export const contractHash = '+JSON.stringify(hash)+';\n'+
    'export const resources = '+JSON.stringify(resources,null,2)+' as const satisfies readonly ResourceModel[];\n';
  const readers=Object.fromEntries(Object.entries(readModelOutputs(document,raw.resources)).map(([name,bytes])=>[name,HEADER+bytes]));
  const requestSource=HEADER+'import type { RequestModel } from "@mpfrontend/ftg-core";\n'+
    'export const contractHash = '+JSON.stringify(hash)+';\n'+
    'export const requests = '+JSON.stringify(requests,null,2)+' as const satisfies readonly RequestModel[];\n';
  const payloads=Object.fromEntries(Object.entries(requestModelOutputs(document,requests)).map(([name,bytes])=>[name,HEADER+bytes]));
  const generated={'resources.gen.ts':source,...readers,'requests.gen.ts':requestSource,...payloads};
  const manifest=JSON.stringify({generator:'FTG',version:GENERATOR_VERSION,irVersion:3,contractHash:hash,
    files:Object.fromEntries(Object.entries(generated).map(([name,bytes])=>[name,digest(bytes)]))},null,2)+'\n';
  const desired:Record<string,string>={...generated,'generation-manifest.json':manifest};
  const marker=join(output,'.ftg-write.lock'),writer=!check&&!dryRun,owner=randomUUID();
  await assertNoWriter(marker);
  if(writer){
    await mkdir(output,{recursive:true});
    try{await writeFile(marker,owner,{flag:'wx'});}
    catch(error){if((error as NodeJS.ErrnoException).code==='EEXIST')throw new InputError('GENERATION_BUSY',4);throw error;}
  }
  try{
  const previous=new Map<string,string|undefined>();
  const changed:string[]=[];
  for(const[name,content]of Object.entries(desired)){
    const file=join(output,name);
    const old=await generatedFile(file);
    if(old!==undefined && (name==='generation-manifest.json'?JSON.parse(old).generator!=='FTG':!old.startsWith(HEADER)))throw new InputError('AUTHORED_FILE_COLLISION',4);
    previous.set(name,old);if(old!==content)changed.push(name);
  }
  if(check && changed.length)throw new InputError('GENERATED_DRIFT',3);
  if(!check && !dryRun && changed.length){
    const staged=new Map<string,string>();const replaced:string[]=[];
    try {
      for(const name of changed){const stage=join(output,'.ftg-'+randomUUID());await writeFile(stage,desired[name]!,{flag:'wx'});staged.set(name,stage);}
      for(const name of changed){
        if(await generatedFile(join(output,name))!==previous.get(name))throw new InputError('GENERATION_FILE_CHANGED',4);
        await rename(staged.get(name)!,join(output,name));staged.delete(name);replaced.push(name);
      }
    }catch(error){
      let conflict=false;
      for(const name of replaced){
        const file=join(output,name);
        if(await generatedFile(file)!==desired[name]){conflict=true;continue;}
        const old=previous.get(name);if(old===undefined)await unlink(file);else await writeFile(file,old);
      }
      if(conflict)throw new InputError('GENERATION_ROLLBACK_CONFLICT',4);
      throw error;
    }finally {for(const stage of staged.values())await unlink(stage).catch(()=>undefined);}
  }
  if(!writer)await assertNoWriter(marker);
  return {ok:true,contractHash:hash,resources:resources.length,requests:requests.length,changed,dryRun,check};
  }finally{
    // Never remove another writer's marker or a marker replaced by an authored symlink.
    if(writer&&await generatedFile(marker)===owner)await unlink(marker);
  }
}
