import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { generate, InputError, loadContract } from '../src/index.js';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';

test('executable CLI reports the package version rather than a stale hard-coded cohort',async()=>{
  const require=createRequire(import.meta.url);
  const metadata=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));
  const result=spawnSync(process.execPath,['--import',require.resolve('tsx'),fileURLToPath(new URL('../src/cli.ts',import.meta.url)),'--version'],{encoding:'utf8'});
  assert.equal(result.status,0,result.stderr);assert.equal(result.stdout.trim(),metadata.version);
});

const contract = {
  openapi: '3.1.0',
  info: { title: 'Fixture', version: '1.0.0' },
  paths: {
    '/items': {
      get: {
        operationId: 'ListItems',
        responses: {
          '200': {
            description: 'Items',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['items'],
                  properties: {
                    items: { type: 'array', items: { $ref: '#/components/schemas/Item' } },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    schemas: {
      Item: {
        type: 'object',
        required: ['id', 'name'],
        properties: { id: { type: 'string', readOnly: true }, name: { type: 'string' } },
      },
    },
  },
};

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), 'mpfrontend-ftg-'));
  // Standalone readers import only their declared Ajv runtime helpers, not the compiler.
  await symlink(fileURLToPath(new URL('../node_modules',import.meta.url)),join(root,'node_modules'),'dir');
  await writeFile(join(root, 'openapi.json'), JSON.stringify(contract));
  await writeFile(join(root, 'ftg.json'), JSON.stringify({
    openapi: 'openapi.json',
    output: 'generated',
    resources: [{ name: 'items', operationId: 'ListItems', responsePath: ['items'] }],
  }));
  return root;
}

test('generation is deterministic and check detects drift', async () => {
  const root = await fixture();
  try {
    const first = await generate(join(root, 'ftg.json'));
    assert.deepEqual(first.changed, ['resources.gen.ts', 'read-models.gen.ts', 'read-validators.gen.cjs', 'read-validators.gen.d.cts', 'requests.gen.ts', 'request-models.gen.ts', 'request-validators.gen.cjs', 'request-validators.gen.d.cts', 'generation-manifest.json']);
    assert.deepEqual((await generate(join(root, 'ftg.json'), { check: true })).changed, []);
    await writeFile(join(root, 'generated', 'resources.gen.ts'), '// @generated by FTG; edit authored overrides instead.\nchanged\n');
    await assert.rejects(generate(join(root, 'ftg.json'), { check: true }), (error: unknown) =>
      error instanceof InputError && error.exitCode === 3 && error.message === 'GENERATED_DRIFT');
    assert.match(await readFile(join(root, 'generated', 'generation-manifest.json'), 'utf8'), /"contractHash"/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('generated full-response readers enforce constraints, formats and read-only direction without mutating data',async()=>{
  const root=await fixture();
  try{
    const constrained=structuredClone(contract);
    constrained.components.schemas.Item={type:'object',additionalProperties:false,required:['id','name','secret'],properties:{
      id:{type:'string',format:'uuid',readOnly:true},name:{type:'string',minLength:2,maxLength:20},
      secret:{type:'string',writeOnly:true},note:{type:['string','null']},
      tags:{type:'array',items:{type:'string'},maxItems:2},count:{type:'integer',minimum:1},
      occurredOnUtc:{type:'string',format:'date-time'}
    }} as never;
    await writeFile(join(root,'openapi.json'),JSON.stringify(constrained));
    await generate(join(root,'ftg.json'));
    const validators=createRequire(import.meta.url)(join(root,'generated','read-validators.gen.cjs'));
    const good={items:[{id:'b50c40a4-fb7b-4ea1-926f-fc9e3df50d25',name:'Readable',note:null,tags:['a'],count:1,occurredOnUtc:'2026-10-07T05:00:00Z'}]};
    const before=structuredClone(good);
    assert.equal(validators.items(good),true);
    for(const bad of [{items:[{...good.items[0],id:'not-uuid'}]},
      {items:[{...good.items[0],name:'x'}]}, {items:[{...good.items[0],secret:'never-return-this'}]},
      {items:[{...good.items[0],count:'1'}]}, {items:[{...good.items[0],count:0}]},
      {items:[{...good.items[0],tags:['a','b','c']}]}, {items:[{...good.items[0],extra:true}]},
      {items:[{...good.items[0],occurredOnUtc:'yesterday'}]}]){
      assert.equal(validators.items(bad),false);
    }
    assert.deepEqual(good,before);
    const types=await readFile(join(root,'generated','read-models.gen.ts'),'utf8');
    assert.match(types,/export type ReadModels/);assert.match(types,/readonly "items"/);
    assert.match(types,/"note"\?: string \| null/);assert.doesNotMatch(types,/"secret"/);
    const source=await readFile(join(root,'generated','read-validators.gen.cjs'),'utf8');
    assert.doesNotMatch(source,/new Function\(|\beval\(/);
    assert.deepEqual((await generate(join(root,'ftg.json'),{check:true})).changed,[]);
  }finally{await rm(root,{recursive:true,force:true});}
});

test('external references fail before generation', async () => {
  const root = await fixture();
  try {
    const external = structuredClone(contract);
    external.components.schemas.Item.properties.name = { $ref: 'https://invalid.example/name.json' } as never;
    await writeFile(join(root, 'external.json'), JSON.stringify(external));
    await assert.rejects(loadContract(join(root, 'external.json')), /EXTERNAL_REFS_REQUIRE_PINNED_BUNDLE/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('a generated-file symlink is rejected without touching its target', async () => {
  const root = await fixture();
  try {
    await mkdir(join(root, 'generated'));
    const outside = join(root, 'authored.ts');
    await writeFile(outside, 'authored\n');
    await symlink(outside, join(root, 'generated', 'resources.gen.ts'));
    await assert.rejects(generate(join(root, 'ftg.json')), (error: unknown) =>
      error instanceof InputError && error.exitCode === 4 && error.message === 'GENERATED_FILE_SYMLINK');
    assert.equal(await readFile(outside, 'utf8'), 'authored\n');
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('a pending generation marker refuses write, check and dry-run without disturbing its owner',async()=>{
  const root=await fixture();
  try{
    await generate(join(root,'ftg.json'));
    const marker=join(root,'generated','.ftg-write.lock');
    const before=await readFile(join(root,'generated','resources.gen.ts'),'utf8');
    await writeFile(marker,'other-writer');
    for(const options of [{},{check:true},{dryRun:true}])await assert.rejects(generate(join(root,'ftg.json'),options),/GENERATION_BUSY/);
    assert.equal(await readFile(marker,'utf8'),'other-writer');
    assert.equal(await readFile(join(root,'generated','resources.gen.ts'),'utf8'),before);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('explicit request contracts emit separate typed payloads and reject read-only, unknown and malformed fields',async()=>{
  const root=await fixture();
  try{
    const body={type:'object',additionalProperties:false,required:['name','password','serverId'],properties:{
      name:{type:'string',minLength:2,maxLength:20},password:{type:'string',writeOnly:true,minLength:8},
      serverId:{type:'string',readOnly:true},quantity:{type:'integer',minimum:1},
      note:{type:['string','null']},contact:{type:'object',additionalProperties:false,required:['email'],properties:{email:{type:'string',format:'email'},created:{type:'string',readOnly:true}}}
    }};
    const doc=structuredClone(contract) as unknown as Record<string,unknown>;
    const paths=doc.paths as Record<string,Record<string,unknown>>;
    paths['/items']!.post={operationId:'CreateItem',requestBody:{required:true,content:{'application/json':{schema:body}}},responses:{'201':{description:'Created'}}};
    await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[{name:'items',operationId:'ListItems',responsePath:['items']}],requests:[{name:'create-item',operationId:'CreateItem'}]}));
    await generate(join(root,'ftg.json'));
    const validators=createRequire(import.meta.url)(join(root,'generated','request-validators.gen.cjs'));
    const good={name:'Item',password:'synthetic',quantity:1,note:null,contact:{email:'example@example.invalid'}};
    const before=structuredClone(good);assert.equal(validators['create-item'](good),true);
    for(const bad of [{...good,name:'x'},{...good,password:undefined},{...good,serverId:'server-owned'},
      {...good,quantity:'1'},{...good,quantity:0},{...good,extra:'not-selected'},
      {...good,contact:{email:'invalid'}},{...good,contact:{...good.contact,created:'server-owned'}}])assert.equal(validators['create-item'](bad),false);
    assert.deepEqual(good,before);
    const types=await readFile(join(root,'generated','request-models.gen.ts'),'utf8');
    assert.match(types,/export type RequestModels/);assert.match(types,/"password": string/);assert.doesNotMatch(types,/serverId|created/);
    const metadata=await readFile(join(root,'generated','requests.gen.ts'),'utf8');assert.match(metadata,/"editable": true/);
    const reader=await import(pathToFileURL(join(root,'generated','read-models.gen.ts')).href);
    const writer=await import(pathToFileURL(join(root,'generated','request-models.gen.ts')).href);
    assert.throws(()=>reader.parseRead('constructor',{}),/INVALID_API_RESPONSE/);
    assert.throws(()=>writer.parseRequest('constructor',{}),/INVALID_API_REQUEST/);
    assert.deepEqual(writer.parseRequest('create-item',good),good);
    assert.deepEqual((await generate(join(root,'ftg.json'),{check:true})).changed,[]);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('request generation refuses open object payloads rather than inventing an allowlist or dropping constraints',async()=>{
  const root=await fixture();
  try{
    const doc=structuredClone(contract) as unknown as Record<string,unknown>;
    (doc.paths as Record<string,Record<string,unknown>>)['/items']!.post={operationId:'CreateItem',requestBody:{required:true,content:{'application/json':{schema:{type:'object',properties:{name:{type:'string'}}}}}},responses:{'201':{description:'Created'}}};
    await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[],requests:[{name:'create-item',operationId:'CreateItem'}]}));
    await assert.rejects(generate(join(root,'ftg.json')),/REQUEST_OBJECT_MUST_DECLARE_CLOSED_PROPERTIES/);
    await assert.rejects(readFile(join(root,'generated','requests.gen.ts')),{code:'ENOENT'});
  }finally{await rm(root,{recursive:true,force:true});}
});
test('JSON success status is explicit; 201 and 202 do not masquerade as 200 or grant form editability',async()=>{
  for(const status of ['201','202']){
    const root=await fixture();
    try{
      const doc=structuredClone(contract) as unknown as Record<string,unknown>;
      (doc.paths as Record<string,Record<string,unknown>>)['/items']!.post={operationId:'SubmitItem',responses:{[status]:{description:'Accepted',content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['id'],properties:{id:{type:'string',format:'uuid'}}}}}}}};
      await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
      const selection={name:'submission',operationId:'SubmitItem',responseStatus:status};
      await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[selection]}));
      await generate(join(root,'ftg.json'));
      const {parseRead}=await import(pathToFileURL(join(root,'generated','read-models.gen.ts')).href);
      assert.deepEqual(parseRead('submission',{id:'b50c40a4-fb7b-4ea1-926f-fc9e3df50d25'}),{id:'b50c40a4-fb7b-4ea1-926f-fc9e3df50d25'});
      assert.throws(()=>parseRead('submission',{id:'invalid'}),/INVALID_API_RESPONSE/);
      const resources=await readFile(join(root,'generated','resources.gen.ts'),'utf8');
      assert.match(resources,new RegExp('"responseStatus": "'+status+'"'));assert.doesNotMatch(resources,/"editable": true/);
      for(const bad of [{name:'submission',operationId:'SubmitItem'}, {...selection,responseStatus:'400'}]){
        await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[bad]}));
        await assert.rejects(generate(join(root,'ftg.json')),/MISSING_JSON_RESPONSE|UNSUPPORTED_JSON_SUCCESS_STATUS/);
      }
    }finally{await rm(root,{recursive:true,force:true});}
  }
});
test('zero selected requests or responses compile strictly and reject every parser call',async()=>{
  const root=await fixture();
  try{
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[],requests:[]}));
    await generate(join(root,'ftg.json'));
    const readers=await import(pathToFileURL(join(root,'generated','read-models.gen.ts')).href);
    const inputs=await import(pathToFileURL(join(root,'generated','request-models.gen.ts')).href);
    assert.throws(()=>readers.parseRead('constructor',{}),/INVALID_API_RESPONSE/);
    assert.throws(()=>inputs.parseRequest('constructor',{}),/INVALID_API_REQUEST/);
    const compiler=createRequire(import.meta.url).resolve('typescript/bin/tsc');
    const checked=spawnSync(process.execPath,[compiler,'--target','ES2023','--module','NodeNext','--moduleResolution','NodeNext','--strict','--skipLibCheck','--noEmit',join(root,'generated','read-models.gen.ts'),join(root,'generated','request-models.gen.ts')],{encoding:'utf8'});
    assert.equal(checked.status,0,checked.stdout+checked.stderr);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('explicit bodyless mutation emits undefined, not an empty JSON object, beside strict JSON requests',async()=>{
  const root=await fixture();
  try{
    const doc=structuredClone(contract) as unknown as Record<string,unknown>,paths=doc.paths as Record<string,Record<string,unknown>>;
    paths['/items']!.delete={operationId:'RemoveItem',responses:{'200':{description:'Removed'}}};
    paths['/items']!.post={operationId:'CreateItem',requestBody:{required:true,content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['approved'],properties:{approved:{type:'boolean'}}}}}},responses:{'201':{description:'Created'}}};
    await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[],requests:[
      {name:'remove-item',operationId:'RemoveItem',body:'none'},{name:'create-item',operationId:'CreateItem'}
    ]}));
    await generate(join(root,'ftg.json'));
    const {parseRequest}=await import(pathToFileURL(join(root,'generated/request-models.gen.ts')).href);
    assert.equal(parseRequest('remove-item',undefined),undefined);
    for(const value of [{},null,'',false,0,[],{approved:false}])assert.throws(()=>parseRequest('remove-item',value),/INVALID_API_REQUEST/);
    assert.throws(()=>parseRequest('constructor',undefined),/INVALID_API_REQUEST/);
    assert.deepEqual(parseRequest('create-item',{approved:false}),{approved:false});assert.throws(()=>parseRequest('create-item',undefined),/INVALID_API_REQUEST/);
    const validators=createRequire(import.meta.url)(join(root,'generated/request-validators.gen.cjs'));
    assert.equal(validators['remove-item'](undefined),true);assert.equal(validators['remove-item']({}),false);
    assert.match(await readFile(join(root,'generated/request-models.gen.ts'),'utf8'),/"remove-item": undefined;/);
    assert.match(await readFile(join(root,'generated/requests.gen.ts'),'utf8'),/"body": "none"/);
    const compiler=createRequire(import.meta.url).resolve('typescript/bin/tsc');
    const checked=spawnSync(process.execPath,[compiler,'--target','ES2023','--module','NodeNext','--moduleResolution','NodeNext','--strict','--skipLibCheck','--noEmit',join(root,'generated/request-models.gen.ts')],{encoding:'utf8'});
    assert.equal(checked.status,0,checked.stdout+checked.stderr);
    assert.deepEqual((await generate(join(root,'ftg.json'),{check:true})).changed,[]);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('explicit optional JSON emits an absent, null or schema-valid payload without accepting an empty object',async()=>{
  const root=await fixture();
  try{
    const doc=structuredClone(contract) as unknown as Record<string,unknown>,paths=doc.paths as Record<string,Record<string,unknown>>;
    paths['/items']!.post={operationId:'CancelItem',requestBody:{required:false,content:{'application/json':{schema:{oneOf:[{type:'null'},{type:'object',additionalProperties:false,required:['note'],properties:{note:{type:['string','null']}}}]}}}},responses:{'200':{description:'Cancelled'}}};
    await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[],requests:[
      {name:'cancel-item',operationId:'CancelItem',body:'optional-json'}
    ]}));
    await generate(join(root,'ftg.json'));
    const {parseRequest}=await import(pathToFileURL(join(root,'generated/request-models.gen.ts')).href);
    for(const value of [undefined,null,{note:null},{note:'customer request'}])assert.deepEqual(parseRequest('cancel-item',value),value);
    for(const value of [{},{note:3},{note:null,extra:true},'',false,0,[]])assert.throws(()=>parseRequest('cancel-item',value),/INVALID_API_REQUEST/);
    const validators=createRequire(import.meta.url)(join(root,'generated/request-validators.gen.cjs'));
    assert.equal(validators['cancel-item'](undefined),true);assert.equal(validators['cancel-item'](null),true);assert.equal(validators['cancel-item']({}),false);
    assert.match(await readFile(join(root,'generated/request-models.gen.ts'),'utf8'),/"cancel-item": .*undefined/);
    assert.match(await readFile(join(root,'generated/requests.gen.ts'),'utf8'),/"body": "optional-json"/);
    const compiler=createRequire(import.meta.url).resolve('typescript/bin/tsc');
    const checked=spawnSync(process.execPath,[compiler,'--target','ES2023','--module','NodeNext','--moduleResolution','NodeNext','--strict','--skipLibCheck','--noEmit',join(root,'generated/request-models.gen.ts')],{encoding:'utf8'});
    assert.equal(checked.status,0,checked.stdout+checked.stderr);
    assert.deepEqual((await generate(join(root,'ftg.json'),{check:true})).changed,[]);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('explicit empty 204 response emits undefined and rejects every value or non-empty response profile',async()=>{
  const root=await fixture();
  try{
    const doc=structuredClone(contract) as unknown as Record<string,unknown>,paths=doc.paths as Record<string,Record<string,unknown>>;
    paths['/items']!.post={operationId:'ReportPosition',requestBody:{required:true,content:{'application/json':{schema:{type:'object',additionalProperties:false,required:['latitude','longitude'],properties:{latitude:{type:'number'},longitude:{type:'number'}}}}}},responses:{'204':{description:'No Content'}}};
    await writeFile(join(root,'openapi.json'),JSON.stringify(doc));
    await writeFile(join(root,'ftg.json'),JSON.stringify({openapi:'openapi.json',output:'generated',resources:[
      {name:'report-position',operationId:'ReportPosition',responseStatus:'204',body:'none'}
    ],requests:[{name:'report-position',operationId:'ReportPosition'}]}));
    await generate(join(root,'ftg.json'));
    const {parseRead}=await import(pathToFileURL(join(root,'generated/read-models.gen.ts')).href);
    assert.equal(parseRead('report-position',undefined),undefined);
    for(const value of [{},null,'',false,0,[]])assert.throws(()=>parseRead('report-position',value),/INVALID_API_RESPONSE/);
    assert.throws(()=>parseRead('constructor',undefined),/INVALID_API_RESPONSE/);
    const validators=createRequire(import.meta.url)(join(root,'generated/read-validators.gen.cjs'));
    assert.equal(validators['report-position'](undefined),true);assert.equal(validators['report-position'](null),false);
    assert.match(await readFile(join(root,'generated/read-models.gen.ts'),'utf8'),/"report-position": undefined;/);
    const resources=await readFile(join(root,'generated/resources.gen.ts'),'utf8');
    assert.match(resources,/"responseStatus": "204"/);assert.match(resources,/"body": "none"/);assert.doesNotMatch(resources,/"schema"/);
    const compiler=createRequire(import.meta.url).resolve('typescript/bin/tsc');
    const checked=spawnSync(process.execPath,[compiler,'--target','ES2023','--module','NodeNext','--moduleResolution','NodeNext','--strict','--skipLibCheck','--noEmit',join(root,'generated/read-models.gen.ts')],{encoding:'utf8'});
    assert.equal(checked.status,0,checked.stdout+checked.stderr);
    assert.deepEqual((await generate(join(root,'ftg.json'),{check:true})).changed,[]);
  }finally{await rm(root,{recursive:true,force:true});}
});
