import {lstat,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
export type DesignSource='none'|'existing';
export type WorkspaceOptions={name:string;directory:string;designSource?:DesignSource;dryRun?:boolean};
const json=(value:unknown)=>JSON.stringify(value,null,2)+'\n';
/** A neutral Nx/pnpm shell only. Backend contracts, secrets and deployment decisions are not invented. */
export function workspaceFiles(name:string,designSource:DesignSource='none'):Record<string,string>{
  if(!/^[a-z][a-z0-9-]{1,48}$/.test(name))throw new Error('INVALID_WORKSPACE_NAME');
  if(!['none','existing'].includes(designSource))throw new Error('INVALID_DESIGN_SOURCE');
  const designStatus=designSource==='none'?'disabled':'pending';
  return {
    'package.json':json({name,private:true,type:'module',packageManager:'pnpm@11.25.0',engines:{node:'>=24 <25'},
      scripts:{build:'nx run-many -t build',check:'nx run-many -t build typecheck generated-check'},
      devDependencies:{'@mpfrontend/ftg-cli':'0.1.0-dev.18',nx:'23.2.1',typescript:'5.9.3','@types/node':'24.10.1','@types/react':'19.3.0','@types/react-dom':'19.2.3'}}),
    'pnpm-workspace.yaml':'packages:\n  - apps/*\n  - packages/*\n  - themes/*\noverrides:\n  axios@1.18.1: 1.20.0\n  brace-expansion@5.0.9: 5.0.12\n  smol-toml@1.6.1: 1.9.0\nallowBuilds:\n  "@scarf/scarf": false\n  esbuild: true\n  nx: true\n  sharp: true\n  unrs-resolver: true\n',
    'nx.json':json({namedInputs:{default:['{projectRoot}/**/*','!{projectRoot}/.next/**/*','!{projectRoot}/node_modules/**/*','!{projectRoot}/runtime-assets/**/*'],
      sharedGlobals:['{workspaceRoot}/pnpm-lock.yaml','{workspaceRoot}/package.json','{workspaceRoot}/pnpm-workspace.yaml']},
      targetDefaults:{build:{inputs:['default','sharedGlobals'],cache:true},typecheck:{inputs:['default','sharedGlobals'],cache:true}}}),
    '.gitignore':'node_modules/\n.next/\n.nx/\nruntime-assets/\n*.tsbuildinfo\n.env\n.env.*\n!.env.example\n.mpfrontend/skills-install.lock\n.ftg-write.lock\n',
    '.mpfrontend/workspace.json':json({schemaVersion:1,name,orchestrator:'nx',packageManager:'pnpm',runtimeProfile:'unconfigured',designSource,cliVersion:'0.1.0-dev.18'}),
    '.mpfrontend/design-source.json':json({schemaVersion:1,generator:'MPFrontendDesignSource',cliVersion:'0.1.0-dev.18',source:designSource,status:designStatus,binding:null,bindingHash:null,sourceIdentity:null,release:null}),
    'apps/.gitkeep':'','packages/.gitkeep':'','themes/.gitkeep':'',
    'contracts/README.md':'# API ownership\n\nSupply an approved, immutable OpenAPI bundle under openapi/presentation/<app>/openapi.json.\nThe generated catalog example expects listCatalog; configure FTG explicitly for your actual contract.\nNo backend API, permissions or production runtime is generated by workspace initialization.\n',
    'AGENTS.md':'# Consumer workspace\n\nUse pnpm and Nx. Product behavior, DLS bindings and assets stay in this repository; MP Frontend core remains product-neutral.\nRead the README and approved API/design contracts before changing behavior. Preserve authored overrides.\nNever commit secrets or claim production readiness from a scaffold/build alone.\nRepository skills are installed explicitly with mpfrontend skills install; no global configuration is changed.\n',
    'CLAUDE.md':'@AGENTS.md\n',
    'README.md':`# ${name}\n\nNeutral MP Frontend Nx/pnpm workspace, initialized with design source \`${designSource}\` without installing dependencies or creating Git history.\n\n1. Install the pinned dependencies with pnpm install. Unpublished development packages require the tested local artifact overrides; no npm availability is claimed.\n2. ${designSource==='none'?'Continue code-first, or attach an approved consumer-owned design source later with mpfrontend design attach.':'Create an approved root design.binding.json for the consumer-owned DLS, then complete the pending source with mpfrontend design attach.'}\n3. Run pnpm exec mpfrontend create app --name customer --directory apps/customer.\n4. Supply your approved catalog OpenAPI contract as explained in contracts/README.md.\n5. Install application dependencies, then run pnpm check. Review pnpm-lock.yaml and use frozen installs in CI.\n6. Run pnpm exec mpfrontend skills install --for both --profile base only if repository-scoped agent workflows are wanted. The catalog provides eighteen finite workflows; the base profile installs fourteen.\n\nDesign source modes are explicit: \`existing\` attaches a consumer-owned DLS binding and \`none\` remains code-first. MP Frontend does not ship or require a public Community DLS in this release. Initialization never reads, captures or changes Figma.\n\nThe catalog template is not a protected production application. Configure the security BFF, identity, gateway and realtime boundaries with acceptance tests before protected product adoption.\nProduct DLS, fonts, themes, locale policy, exports, mappings and asset rights are consumer-owned. No Figma access/write, watcher, Git operation, deployment, package publication or global installation is performed.\n\nExisting destinations are refused, including an empty directory or symlink. A filesystem failure may leave a partial new destination for inspection; it is never automatically deleted or retried over.\n`,
  };
}
export async function createWorkspace(options:WorkspaceOptions){
  const designSource=options.designSource??'none',files=workspaceFiles(options.name,designSource),directory=resolve(options.directory);
  try{await lstat(directory);throw new Error('DESTINATION_EXISTS');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  if(!options.dryRun){
    // Exclusive directory creation refuses a competing creator; writes never replace an existing file.
    await mkdir(directory,{recursive:false});
    for(const [path,content] of Object.entries(files)){const target=join(directory,path);await mkdir(dirname(target),{recursive:true});await writeFile(target,content,{flag:'wx'});}
  }
  return {ok:true,name:options.name,directory,files:Object.keys(files).sort(),dryRun:options.dryRun===true,runtimeProfile:'unconfigured',designSource};
}
